### ISSUE TITLE
[FR] Is it possible to keep the `db.tsv` cluster file

### ISSUE THREAD

**Issue by camilogarciabotero** [chg60/phammseqs#2] opened 2024-03-07 21:33 UTC
Hi @chg60 ,

Thanks for working on `phamsseqs`. I was wondering if it is possible to keep the [db.tsv cluster file](https://github.com/soedinglab/MMseqs2/wiki#cluster-tsv-format) from the `mmseqs` output, after running the program. I meant the one that looks like this:

```bash
#cluster-representative 	cluster-member
Q0KJ32	Q0KJ32
Q0KJ32	C0W539
Q0KJ32	D6KVP9
E3HQM9	E3HQM9
E3HQM9	F0YHT8
```

Or maybe having a script that modifies the `cluster-representative` with the `pham` output could be nice? 

I was trying to create such a script, but after so many files from the final `phamsseqs` output, another script parsing each file increases the runtime overall. So maybe it would be more convenient to have that from the current tool.

Best.

**Comment by chg60** [comment] 2024-03-07 22:03
Hi Camilo,

Thanks for your interest in PhaMMseqs!

I agree that there is likely broad utility to be gained by exposing each pham's representative a bit more easily, and such a file could be easily generated.

How do you intend to use this information? I ask because the MMseqs2 version (13.45111) currently used by PhaMMseqs does the representative sequence selection pretty lazily, so the "representative" chosen by MMseqs2 is often not very representative of the sequences in the pham. If that matters to your intended workflow/analyses, I would be inclined to implement a strategy that uses the pham MSAs rather than that MMseqs TSV file to choose representatives.

Also note that for iterative pham-building that uses the profile-sequence clustering, phams can get rather diverse, so even in the context of an MSA it may not be feasible to choose a truly representative sequence, but likely still better than MMseqs2 chose :)

Finally, in your ideal scenario, would the output file in question be a TSV file like you linked, or some other format?

-Christian

**Comment by camilogarciabotero** [comment] 2024-03-07 22:38
Hey Christian,

Thanks for the quick response.

> The representative sequence selection pretty lazily, so the "representative" chosen by MMseqs2 is often not very representative of the sequences in the pham.

Oh, I might then misunderstood the pham creation. So it is not the same as the representative of the `mmeseqs`, right?

> How do you intend to use this information?

I just want to visualize the clusters and happens to be easier with the `tsv` file for me. I then would be inclined for an analogous output:

```
#phamm-representative 	cluster-member
pham1	Q0KJ32
pham2	C0W539
pham3	D6KVP9
pham3	E3HQM9
pham3	F0YHT8
```
*without the header

Best.

**Comment by chg60** [comment] 2024-03-08 00:42
I think maybe I'm simply not understanding your circumstances and needs very well. Can you provide a bit more detail about what you're working on? How many input files, containing how many genes/genomes from which kind(s) of organisms, and the type of cluster visualization you're looking to do (i.e., are you really moving toward genome clusters, using gene clusters to identify pairwise relations between genomes)?

> Oh, I might then misunderstood the pham creation. So it is not the same as the representative of the `mmeseqs`, right?

Right, MMseqs is used to identify clusters of globally homologous protein sequences, which are then assigned the same label (i.e., `pham1`). PhaMMseqs was intended to generate those groupings using thresholds curated for phage genomics, where intergenomic comparisons can span great evolutionary distances.

The pham designation is essentially meaningless except that it gives a shared label to all groups of globally homologous protein sequences in the dataset, same as would be true for the representative-to-member mapping. If you're looking to do work that actually cares about what the representative sequence is, then I can implement a strategy to extract that information in as biologically meaningful a way as possible. If all you care about is a TSV format mapping shared genes by genome (which is what your second example makes me think), can you try running with the `-p/--pangenome` flag and see whether the `strain_genes.tsv` or `gene_presence_absence.csv` accomplishes what you're after?

**Comment by camilogarciabotero** [comment] 2024-03-08 01:12
> I think maybe I'm simply not understanding your circumstances and needs very well. Can you provide a bit more detail about what you're working on?

Yes. I am just playing around for the time being with the program using phage proteins. I do have, for instance, the following output from `phammseqs`. This is a `pham_1.faa`

```
>seqa
GESLLLWGEPGNGKTHLAAAIVNELSKKGYIVVFQSVPELLQRIRSTFNSENKENETQIMRALLECDLLILDDIGAEKTT...
>seqb
GESLLLWGEPGNGKTHLAAAIVNELSKKGYIVVFQSVPELLQRIRSTFNSENKENETQIMRALLECDLLILDDIGAEKTT...
```

And also have a `pham_2.faa`

```
>seqc
GESLLLWGEPGNGKTHLAAAIVNELSKKGYIVVFQSVPELLQRIRSTFNSENKENETQIMRALLECDLLILDDIGAEKTT...
>seqd
GESLLLWGEPGNGKTHLAAAIVNELSKKGYIVVFQSVPELLQRIRSTFNSENKENETQIMRALLECDLLILDDIGAEKTT...
>seqe
GESLLLWGEPGNGKTHLAAAIVNELSKKGYIVVFQSVPELLQRIRSTFNSENKENETQIMRALLECDLLILDDIGAEKTT...
```

Now, in my case, I want to visualize the clusters of phams using a graph representation. Ideally, my input would look like this:

```
pham_1    seqa
pham_1    seqb
pham_2    seqc
pham_2    seqd
pham_2    seqe 
```

> Right, MMseqs is used to identify clusters of globally homologous protein sequences, which are then assigned the same label (i.e., pham1). PhaMMseqs was intended to generate those groupings using thresholds curated for phage genomics, where intergenomic comparisons can span great evolutionary distances.

Oh I see, I need to read the docs/paper more carefully.

**Comment by chg60** [comment] 2024-03-08 01:39
To coerce the phammseqs output to what it sounds like you're after, you can use the attached script (just take the `.txt` extension off and activate your PhaMMseqs environment before running).

[phams_to_tsv.py.txt](https://github.com/chg60/phammseqs/files/14532102/phams_to_tsv.py.txt)

It takes the path to the `pham_fastas` directory output by PhaMMseqs and returns a TSV mapping phamID to gene header as seems to be indicated in your example. See if that suits your needs!

On my laptop it takes less than a second for 15,000 phams, I don't expect it to be painful unless you have hundreds of thousands of phams.

**Comment by camilogarciabotero** [comment] 2024-03-08 01:57
Wow, thanks Christian. I will try that out. Would you consider that to be part of the main app or is it very idiosyncratic?

**Comment by chg60** [comment] 2024-03-08 02:15
I hope it delivers what you're looking for! If yes, it's definitely not a typical use case, but if you think there are other people like yourself that would benefit from it, I could maybe see adding a command line arg to output this TSV by default. Make sure it does what you want, then report back! :)

**Comment by camilogarciabotero** [comment] 2024-03-08 02:32
Yes! That is delivering the expected output. Thank you!

**Comment by chg60** [comment] 2024-03-08 14:17
Excellent! I think since it's outside the scope of my typical users' needs, I will not implement the feature yet in the main package. However, I'll re-evaluate if I get more requests like this in the future.

Happy pham assembly!

**Closed as completed by chg60** 2024-03-08 14:17 UTC

**Comment by camilogarciabotero** [comment] 2024-03-09 01:07
Thanks again Christian.
